export default {
    flight: [],
    flights: [{
            _id: "1",
            origin: "Colombia - (Bogotá)",
            destination: "Mexico - (Mexico City)",
            capacity: 25,
            date: "2016-05-18T16:00:00.000Z",
            occupiedSeats: 3,
            isFull: false,
        },
        {
            _id: "2",
            origin: "Colombia - (Bogotá)",
            destination: "Mexico - (Mexico City)",
            capacity: 25,
            date: "2016-05-18T16:00:00.000Z",
            occupiedSeats: 3,
            isFull: false,
        },
        {
            _id: "3",
            origin: "Colombia - (Bogotá)",
            destination: "Mexico - (Mexico City)",
            capacity: 25,
            date: "2016-05-18T16:00:00.000Z",
            occupiedSeats: 3,
            isFull: false,
        },
        {
            _id: "4",
            origin: "Colombia - (Bogotá)",
            destination: "Mexico - (Mexico City)",
            capacity: 25,
            date: "2016-05-18T16:00:00.000Z",
            occupiedSeats: 3,
            isFull: false,
        },
        {
            _id: "5",
            origin: "Colombia - (Bogotá)",
            destination: "Mexico - (Mexico City)",
            capacity: 25,
            date: "2016-05-18T16:00:00.000Z",
            occupiedSeats: 3,
            isFull: false,
        },
    ],
};